sonar.projectKey=ems-fullstack

# Backend
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

# Frontend
sonar.sources+=frontend/src
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info