spring.application.name=backend
server.port=9876
#server.address=127.0.0.1

# ===============================
# MYSQL DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Mysql@123 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.connections.internal=DEBUG
logging.level.org.hibernate.orm.jdbc=DEBUG


# ===============================
# POSTGRESQL DATABASE CONFIG
# ===============================

#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.username=postgres
#spring.datasource.password=Postgres@123
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable Prometheus metrics
management.prometheus.metrics.export.enabled=true

# Optional: show health details
management.endpoint.health.show-details=always
